# Generated by Django 5.1.2 on 2024-11-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('beneficiaries', '0002_beneficiary_education_beneficiary_occupation_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('service', 'beneficiary')},
        ),
    ]
