# Generated by Django 5.1.2 on 2025-01-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
