# Generated by Django 5.1.2 on 2024-11-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_unique_together'),
        ('beneficiaries', '0002_beneficiary_education_beneficiary_occupation_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='service',
        ),
        migrations.AddField(
            model_name='activity',
            name='beneficiary',
            field=models.ManyToManyField(to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='activity',
            name='service',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
