# Generated by Django 5.1.2 on 2024-11-12 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_unique_together_and_more'),
        ('beneficiaries', '0002_beneficiary_education_beneficiary_occupation_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='service',
        ),
        migrations.AddField(
            model_name='activity',
            name='beneficiary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
    ]
