# Generated by Django 5.1.2 on 2024-11-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_activity_beneficiary_remove_activity_service_and_more'),
        ('beneficiaries', '0002_beneficiary_education_beneficiary_occupation_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('service', 'beneficiary')},
        ),
    ]
