# Generated by Django 5.1.2 on 2024-11-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
    ]
