# Generated by Django 5.1.2 on 2024-12-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
