# Generated by Django 5.1.2 on 2024-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='education',
            field=models.CharField(choices=[('None', 'None'), ('Primary', 'Primary'), ('Intermediate', 'Intermediate'), ('Secondary', 'Secondary'), ('Collage-University', 'Collage-University'), ('Post Grad', 'Post Grad')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='occupation',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='disability_in_household',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
