# Generated by Django 5.1.2 on 2024-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_beneficiary_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='images/qrs/'),
        ),
    ]
