# Generated by Django 5.1.2 on 2024-11-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_education_beneficiary_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
