# Generated by Django 5.1.2 on 2024-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiary_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
