# Generated by Django 5.1.2 on 2024-12-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0006_alter_beneficiary_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='qr_code',
        ),
    ]
