# Generated by Django 5.1.2 on 2025-01-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0007_remove_beneficiary_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
