# Generated by Django 5.1.2 on 2024-11-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0005_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
