# Generated by Django 5.1.2 on 2024-11-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0007_alter_profile_managers_profile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
