# Generated by Django 5.1.2 on 2024-11-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0008_alter_profile_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
