# Generated by Django 5.1.2 on 2024-11-10 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('GFA', 'GFA'), ('NFI', 'NFI'), ('WASH', 'WASH'), ('PSS', 'PSS'), ('LEG', 'LEG'), ('LH', 'LH'), ('CD', 'CD')], max_length=50)),
                ('service_description', models.TextField()),
                ('governorate', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('village_neighborhood', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
            ],
        ),
    ]
