# Generated by Django 5.1.2 on 2024-11-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
