# Generated by Django 5.1.2 on 2025-01-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_updated_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
